from emoji import emojize


e_8ball = emojize(' :8ball: ', use_aliases = True)
e_arrow_forward = emojize(' :arrow_forward: ', use_aliases = True)
e_bank = emojize(' :bank: ', use_aliases = True)
e_beginner = emojize(" :beginner:  ", use_aliases=True)
e_confused = emojize(" :confused: ", use_aliases=True)
e_cop = emojize(" :cop: ", use_aliases=True)
e_couple = emojize(' :couple: ', use_aliases = True)
e_creditcard = emojize(' :credit_card: ', use_aliases = True)
e_diamond = emojize(' :small_blue_diamond: ', use_aliases = True)
e_dog = emojize(' :dog: ', use_aliases = True)
e_email = emojize(" :e-mail: ", use_aliases=True)
e_end = emojize(" :end: ", use_aliases=True)
e_envelope = emojize(' :envelope: ', use_aliases = True)
e_dizzy = emojize(" :dizzy:  ", use_aliases=True)
e_floppydisk = emojize(' :floppy_disk: ', use_aliases = True)
e_gem = emojize(" :gem:  ", use_aliases=True)
e_gift_heart = emojize(' :gift_heart: ', use_aliases = True)
e_globe = emojize(" :globe_with_meridians:  ", use_aliases=True)
e_headphones = emojize(" :headphones: ", use_aliases = True)
e_heart = emojize(" :heart: ", use_aliases=True)
e_hourglass = emojize(" :hourglass: ", use_aliases = True)
e_info = emojize("  :information_source: ", use_aliases=True)
e_large_blue_diamond = emojize(" :large_blue_diamond:  ", use_aliases=True)
e_link = emojize(' :link: ', use_aliases = True)
e_lock = emojize(' :lock: ', use_aliases = True)
e_lost = emojize(' :disappointed_relieved: ', use_aliases = True)
e_mag = emojize(' :mag: ', use_aliases = True)
e_memo = emojize(' :memo: ', use_aliases = True)
e_moneybag = emojize(' :moneybag: ', use_aliases = True)
e_moon = emojize(" :crescent_moon:  ", use_aliases=True)
e_name_badge = emojize(" :name_badge:  ", use_aliases=True)
e_new = emojize(" :new: ", use_aliases=True)
e_no = emojize(" :x: ", use_aliases=True)
e_page_with_curl = emojize(" :page_with_curl: ",  use_aliases=True)
e_pager = emojize(' :pager: ', use_aliases = True)
e_plus = emojize(' :heavy_plus_sign: ', use_aliases = True)
e_point_right = emojize(" :point_right: ", use_aliases=True)
e_radio = emojize(" :radio: ", use_aliases=True)
e_radio_button = emojize(" :radio_button:  ", use_aliases=True)
e_scroll = emojize(' :scroll: ', use_aliases = True)
e_spades = emojize(" :spades:  ", use_aliases=True)
e_sparkles = emojize(' :sparkles: ', use_aliases = True)
e_speaker = emojize(" :speaker:  ", use_aliases=True)
e_star = emojize(' :star: ', use_aliases = True)
e_success = emojize(" :heart_eyes: ", use_aliases=True)
e_sunny = emojize(" :sunny:  ", use_aliases=True)
e_tada = emojize(" :tada: ", use_aliases=True)
e_tophat = emojize(' :tophat: ', use_aliases = True)
e_trophy = emojize(' :trophy: ', use_aliases = True)
e_tv = emojize(' :tv: ', use_aliases = True)
e_vhs = emojize(' :vhs: ', use_aliases = True)
e_video_game = emojize(' :video_game: ', use_aliases = True)
e_warning = emojize(" :warning: ", use_aliases=True)
e_white_check_mark = emojize(" :white_check_mark: ", use_aliases=True) 
e_wrench = emojize(" :wrench: ", use_aliases=True)
e_yes = emojize(' :ballot_box_with_check: ', use_aliases = True)
e_zap = emojize(" :zap:  ", use_aliases=True)



